# Generated by Django 5.2.8 on 2025-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_info_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='adress',
            field=models.TextField(max_length=100),
        ),
    ]
