# Generated by Django 5.2.8 on 2025-11-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_info_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='user',
        ),
    ]
