# Generated by Django 5.2.8 on 2025-11-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_info_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student_info',
            constraint=models.UniqueConstraint(fields=('student_class', 'roll'), name='unique_roll_per_class'),
        ),
    ]
